replicaCount: 1
service:
  name: chainlog-ui
  port: 80
  type: ClusterIP
  containerPort: 80
  tls:
    enabled: true
    issuerName: cloudflare
image:
  repository: ${ECR_REGISTRY}/chainlog-ui-prod
  pullPolicy: Always
  tag: prod
serviceAccount:
  create: false
ingress:
  enabled: true
  host: chainlog.makerdao.com
  annotations:
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
podAnnotations:
  reloader.stakater.com/auto: "true"
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 60
env:
  CHECKSUM_CONTAINER_NAME:
    type: kv
    value: "localhost"
readinessProbe:
  tcpSocket:
    port: 80
livenessProbe:
  tcpSocket:
    port: 80
